name: Update Changelog & Release

on:
  push:
    tags:
      - '*'

jobs:
  call-workflow-ft-releases:
    # permissions:
    #   contents: read
    #   pull-requests: write
    uses: figuren-theater/.github/.github/workflows/ft-releases.yml@main
    secrets: inherit # pass all secrets
