name: Draft or update the next release

on:
  push:
    branches:
      - main

jobs:
  call-workflow-release-drafter:
    uses: figuren-theater/.github/.github/workflows/release-drafter.yml@main
    secrets: inherit
